### PR TITLE
Added Base Template for the front-end of SUSI Wiki

### PR DESCRIPTION
**Pull request by dynamitechetan**
For issue #4 
Edit 1:
Screenshot 
image
Link to test project: http://susi_wiki_testing.surge.sh/

### CODE REVIEW

**Comment by saurabhjn76** [comment]
@dynamitechetan Please also include screenshot, nice work :+1:

**Comment by DravitLochan** [comment]
looks nice. Good job :)

**Comment by mariobehling** [comment]
Interesting start, but please implement another design following the chat UI. It is using Material UI.

**Comment by dynamitechetan** [comment]
@mariobehling  design was discussed at https://github.com/fossasia/susi_server/issues/278 so I am following that. Its almost material design, but at some parts where its not material, we will make changes.
Thanks.

**Comment by mariobehling** [comment]
@dynamitechetan Please follow the design of the web chat. We don't need a different design on each component and should rather align. The susi server is still in the loklak design and not a reference.

**Pull request merged**
