### PR TITLE
Added Base Template for Wiki System

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes Issue #4 

**Screenshot for the app**
<table><th>Old</th><th>Updated</th>
<tr><td></td>
<td></td></tr>
</table>

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Can we try dark UI? Dark UI for dashboards looks great. We can still reuse the components from the web chat app.

**Comment by saurabhjn76** [comment]
@dynamitechetan yes this looks great, skill wiki and web chat should look similar. Maybe we can change webchat dark theme like this?

**Comment by mariobehling** [comment]
Please follow the standard UI of the web chat. We need to focus on features and getting this done. We will get designers on board once the basic features are working.

Please use the standard UI of the chat.

**Comment by saurabhjn76** [comment]
@mariobehling :+1:  we will follow web chat UI (light colors)

**Comment by dynamitechetan** [comment]
@mariobehling  changed to a Light theme. Using webchat color scheme.

**Comment by jyoth1raditya** [comment]
@dynamitechetan, Please update the screenshot

**Pull request merged**
